### ISSUE TITLE
Duplicate button

### ISSUE THREAD

**Issue by ModellbahnFreak** [nk-coding/SpaceGame#3]
A button for copiing objects (selections etc) inclding rotation and properties

**Comment by nk-coding** [comment]
implemented with eb10c09c7399cf2437c70fb4ebc111987153e784
use Ctrl + C to copy all selected Components into Clipboard
use Ctrl + V to paste all Components in Clipboard at the current position (if possible)
properties of Components will be copied, including name (this may result in an incorrect ship because names must not be used multiple times)
